# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('played', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delay', models.IntegerField()),
                ('site', models.CharField(choices=[('1', '멜론'), ('2', '벅스'), ('3', '지니')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='song_order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.store'),
        ),
    ]
