# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181019_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song_order',
            new_name='song',
        ),
    ]
