# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181019_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
