# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181024_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='reset_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='reset_played',
            field=models.IntegerField(default=0),
        ),
    ]
