# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181024_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='reset_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 24, 2, 15, 20, 171846, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
