# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181024_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='reset_time',
        ),
        migrations.AddField(
            model_name='song',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
