# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181025_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='reset_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
