# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_store_reset_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='reset_time',
        ),
    ]
